Upadated README.md; Hacktoberfest-2018
LTKills/parallel-programming pull request #7
Opened 2018-10-07 15:17 UTC by preeti98

Please do let me know if you want any specific improvements in this PR. Thank you!
This PR is in reference to issue #2

2018-10-07 17:50 UTC, gmelodie requested changes

2018-10-07 17:50 UTC, LTKills commented on README.md
> +Open MPI is a Message Passing Interface (MPI) library project combining technologies and resources from several other projects (FT-MPI, LA-MPI, LAM/MPI, and PACX-MPI). It is used by many TOP500 super
This could be more directed to MPI itself than to history of OpenMPI

2018-10-07 19:27 UTC, preeti98 commented
I have made  the requested changes. Please do let me know if further modification is required!

2018-10-08 13:51 UTC, gmelodie approved these changes

2018-10-08 13:52 UTC, merged